name: CI Github Actions
on:
  push:
    branches:
    - module_8
  pull_request:
    branches:
    - module_8
jobs:
 build:
  name: Build and test
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - run: echo FixTests
 production:
  needs: build
  name: Publish Image
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/module_8' && github.event_name == 'push'
  steps:
  - run: echo publishing