name: CI Github Actions
on: [push]
jobs:
 build:
  name: Build and test
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - run: docker build --target tests --tag todo-app:tests . 
  - run: docker run todo-app:tests
  - run: docker run -e TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }} -e TRELLO_API_SECRET=${{ secrets.TRELLO_API_SECRET }} -e TRELLO_BOARD_ID=${{ secrets.TRELLO_BOARD_ID }}  todo-app:tests_e2e